dist: xenial
language: php
php: 
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'  
  # cannot make 7.3 work with apache: HTTP header Authorization is not relayed to php-fpm (see build/travis-apache7.3)
  
services:
# make the `mysql` binary available
  - mysql

env:
  # make environment variables available
  # bash: `$SITE_FOLDER` 
  # PHP : `getenv('SITE_FOLDER');` 
  global:
    - DB_NAME="qinoa"
    
before_script:
  # travis DB user is `root`, password is empty and host is `127.0.0.1`
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  # install apache2
  - chmod +x .travis/*.sh
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then .travis/init-php7.3.sh; else .travis/init-php.sh; fi

  
  
script: 
  # check that mandatory directories are present and have correct access rights set
  - php run.php --do=test_fs-consistency
  # check ability to connect to the dbms service
  - php run.php --do=test_db-connectivity
  # initialise database with demo data
  - php run.php --do=init_db --package=core
  # run test units
  - php run.php --do=test_package --package=qinoa
