language: php
php: 
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'  
  
services:
# make the `mysql` binary available
  - mysql

env:
  # make environment variables available
  # bash: `$SITE_FOLDER` 
  # PHP : `getenv('SITE_FOLDER');` 
  global:
    - DB_NAME="qinoa"
    
before_script:
  # travis DB user is `root`, password is empty and host is `127.0.0.1`
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  # install apache2
  - sudo apt-get install apache2 libapache2-mod-fastcgi proxy_fcgi 
  # enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi  
  # - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi    
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  
script: 
  # check that mandatory directories are present and have correct access rights set
  - php run.php --do=test_fs-consistency
  # check ability to connect to the dbms service
  - php run.php --do=test_db-connectivity
  # initialise database with demo data
  - php run.php --do=init_db --package=core
  # run test units
  - php run.php --do=test_package --package=qinoa
